name: Build Android Libraries

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 31
        ndk-version: 23.1.7779620

    - name: Install Dependencies
      run: |
        sudo apt-get install -y build-essential pkg-config

    - name: Build FFmpeg with Custom Libraries
      run: |
        cd ffmpeg-kit/android
        ./android.sh

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ffmpeg-android-build
        path: ffmpeg-kit/prebuilt/android/
